/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.megafon.lobachevsky.app

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testHelloClass() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.run {  }, "app object should not be null")
    }
}
